# Generated by Django 6.0.4 on 2026-04-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_furniture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Review', 'In Review'), ('Approved', 'Approved'), ('In Production', 'In Production'), ('Ready', 'Ready for Delivery'), ('Completed', 'Completed')], default='Pending', max_length=30),
        ),
    ]
