# Generated by Django 6.0.4 on 2026-04-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_customorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=20),
        ),
    ]
