# Generated by Django 6.0.4 on 2026-05-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0004_customorder_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='design_file',
            field=models.FileField(blank=True, null=True, upload_to='design_uploads/'),
        ),
    ]
